package assignment01_test

import (
	"assignment/assignment_01/add"
	"testing"
)

// WARNING: DO NOT EDIT THIS FILE
type addUseCase struct{
	Name string
	Inputs []int
	ExpectedResult int
}
func TestAdder(t *testing.T){
	tests := []struct {
		operation string
		numbers []float64
		expected  float64
	}{
		{"add",[]float64{ 2, 3,7}, 12},
		{"subtract", []float64{5, 3}, 2},
		{"multiply", []float64{2, 3}, 6},
		{"divide", []float64{6, 3}, 2},
	}

	for _, test := range tests {
		result := add.Calculator(test.operation,test.numbers...)
		if result != test.expected {
			t.Errorf("Expected %v but got %v for operation %v with numbers %v", test.expected, result, test.operation, test.numbers)
		}
	}

}